name: CI/CD Pipeline

on:
  push:
    paths-ignore:
     # - 'app/.github/workflows/*'
     # - 'app/app/**' 
      - '**.md' 
      #- '**.yml'
      #- '**.py'
    branches:
      - main
  release:
    types: [created]

jobs:
  build-and-push:
     runs-on: ubuntu-22.04
     steps:
     - name: Login to Docker Hub
       uses: docker/login-action@v1
       with:
         username: ${{ secrets.DOCKERHUB_USER }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
          
     - uses: actions/checkout@v2
      
     - name: Set up Python
       uses: actions/setup-python@v2
       with:
         python-version: '3.x'
      
     - name: Build and push Docker image
       uses: docker/build-push-action@v2
       with:
         context: .
         push: true
         tags: endi7/fastapi001:${{ github.run_number }}
         
  alterar_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: endiseven/gitops
          token: ${{ secrets.GIT_OPS }}

      - name: Set run number
        run: echo "RUN_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV

      - name: Modify yaml File
        run: |
          sed -i "s/^tag: .*/tag: $RUN_NUMBER/" ./fastapi/values.yaml

      - name: Commit and Push Changes
        run: |
          git config user.name "endiseven"
          git config user.email "endi.sete@gmail.com"
          git add ./fastapi/values.yaml
          git commit -m "Update image name in yaml file"
          git push


