name: CI/CD Pipeline

on:
  push:
    paths-ignore:
      - 'app/.github/workflows/*'
      - 'app/app/**' 
      - '**.md' 
      - '**.yml'
      - '**.py'
    branches:
      - main
  release:
    types: [created]

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
      
    - name: Insert DB User into main.py
      run: |
          sed -i 's/\$\{secrets.DATABASE_USER_PASSWORD\}/'"${{ secrets.DATABASE_USER_PASSWORD }}"'/g' main.py
      shell: bash
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: endi7/fastapi001:${{ github.ref_name }}

